# ---- Base ----
FROM node:22-alpine AS base
WORKDIR /app

# ---- Dependencies ----
FROM base AS deps
COPY package.json package-lock.json* ./
RUN npm i --omit=dev

# ---- Production ----
FROM node:22-alpine AS production
WORKDIR /app
ENV NODE_ENV=production
ENV DOTENV_CONFIG_QUIET=true
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 3010
CMD [ "npm", "start" ]
